// <auto-generated />
using System;
using FacturasSRI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturasSRI.Infrastructure.Migrations
{
    [DbContext(typeof(FacturasSRIDbContext))]
    [Migration("20251107022847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacturasSRI.Domain.Entities.AjusteInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadAjustada")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioIdAutoriza")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("AjustesInventario");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.CuentaPorPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Pagada")
                        .HasColumnType("boolean");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("CuentasPorPagar");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContribuyenteEspecial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionMatriz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ObligadoContabilidad")
                        .HasColumnType("boolean");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Establecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalSinImpuestos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FacturaDetalles");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalleConsumoLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadConsumida")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacturaDetalleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacturaDetalleId");

                    b.HasIndex("LoteId");

                    b.ToTable("FacturaDetalleConsumoLotes");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaSRI", b =>
                {
                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaveAcceso")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAutorizacion")
                        .HasColumnType("text");

                    b.Property<string>("RespuestaSRI")
                        .HasColumnType("text");

                    b.Property<string>("RideUrl")
                        .HasColumnType("text");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("text");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("text");

                    b.HasKey("FacturaId");

                    b.ToTable("FacturasSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Impuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoSRI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadComprada")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioCompraUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroNotaCredito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonModificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalSinImpuestos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.ToTable("NotasDeCredito");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("DescuentoAplicado")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NotaDeCreditoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NotaDeCreditoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("NotaDeCreditoDetalles");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoSRI", b =>
                {
                    b.Property<Guid>("NotaDeCreditoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaveAcceso")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAutorizacion")
                        .HasColumnType("text");

                    b.Property<string>("RespuestaSRI")
                        .HasColumnType("text");

                    b.Property<string>("RideUrl")
                        .HasColumnType("text");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("text");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("text");

                    b.HasKey("NotaDeCreditoId");

                    b.ToTable("NotasDeCreditoSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.PrecioEspecial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PreciosEspeciales");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManejaInventario")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManejaLotes")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.ProductoComponente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductoComponenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoKitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoComponenteId");

                    b.HasIndex("ProductoKitId");

                    b.ToTable("ProductoComponentes");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.ProductoImpuesto", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImpuestoId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductoId", "ImpuestoId");

                    b.HasIndex("ImpuestoId");

                    b.ToTable("ProductoImpuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.PuntoEmision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uuid");

                    b.Property<int>("SecuencialFactura")
                        .HasColumnType("integer");

                    b.Property<int>("SecuencialNotaCredito")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.ToTable("PuntosEmision");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<Guid>("PermisosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermisosId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermisoRol");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.AjusteInventario", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.CuentaPorPagar", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Establecimiento", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Establecimientos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Factura", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalleConsumoLote", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.FacturaDetalle", "FacturaDetalle")
                        .WithMany("ConsumosDeLote")
                        .HasForeignKey("FacturaDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaDetalle");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaSRI", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithOne("InformacionSRI")
                        .HasForeignKey("FacturasSRI.Domain.Entities.FacturaSRI", "FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Lote", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCredito", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("NotasDeCredito")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoDetalle", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.NotaDeCredito", "NotaDeCredito")
                        .WithMany("Detalles")
                        .HasForeignKey("NotaDeCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaDeCredito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoSRI", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.NotaDeCredito", "NotaDeCredito")
                        .WithOne("InformacionSRI")
                        .HasForeignKey("FacturasSRI.Domain.Entities.NotaDeCreditoSRI", "NotaDeCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaDeCredito");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.ProductoComponente", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "ProductoComponenteItem")
                        .WithMany()
                        .HasForeignKey("ProductoComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "ProductoKit")
                        .WithMany("Componentes")
                        .HasForeignKey("ProductoKitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoComponenteItem");

                    b.Navigation("ProductoKit");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.ProductoImpuesto", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Impuesto", "Impuesto")
                        .WithMany("ProductoImpuestos")
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany("ProductoImpuestos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impuesto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.PuntoEmision", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Establecimiento", "Establecimiento")
                        .WithMany("PuntosEmision")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("NotasDeCredito");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Establecimientos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Establecimiento", b =>
                {
                    b.Navigation("PuntosEmision");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("InformacionSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Navigation("ConsumosDeLote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Impuesto", b =>
                {
                    b.Navigation("ProductoImpuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCredito", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("InformacionSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Componentes");

                    b.Navigation("Lotes");

                    b.Navigation("ProductoImpuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
