// <auto-generated />
using System;
using FacturasSRI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturasSRI.Infrastructure.Migrations
{
    [DbContext(typeof(FacturasSRIDbContext))]
    [Migration("20251122135819_InitialLocalSeed")]
    partial class InitialLocalSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacturasSRI.Domain.Entities.AjusteInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadAjustada")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioIdAutoriza")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("AjustesInventario", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21ca4714-1575-4499-8a34-77dcd5a63348"),
                            Nombre = "Computadores y Laptops"
                        },
                        new
                        {
                            Id = new Guid("5f4b42c5-14f6-43c3-b2f2-65abbe663943"),
                            Nombre = "Componentes de PC"
                        },
                        new
                        {
                            Id = new Guid("eb9632c7-8e22-483c-b698-d0920fa6f2a6"),
                            Nombre = "Periféricos"
                        },
                        new
                        {
                            Id = new Guid("f5e5e6b4-165c-48bb-8e83-e50a1ad7f5e3"),
                            Nombre = "Redes y Conectividad"
                        },
                        new
                        {
                            Id = new Guid("fcd7e8d6-785a-4ed8-ac0e-18d7d6ba5af6"),
                            Nombre = "Impresión y Suministros"
                        },
                        new
                        {
                            Id = new Guid("0c4b97b5-5ac6-4133-a7d2-d7bf9004da63"),
                            Nombre = "Software y Licencias"
                        },
                        new
                        {
                            Id = new Guid("7e1789d2-4158-4cb9-80d2-3705a293b20b"),
                            Nombre = "Servidores y Enterprise"
                        },
                        new
                        {
                            Id = new Guid("ec8191e3-5a11-4eae-beab-697cafdd99a9"),
                            Nombre = "Accesorios y Cables"
                        },
                        new
                        {
                            Id = new Guid("bbfcc825-676b-4411-bc44-2c83b84a8de4"),
                            Nombre = "Servicios Técnicos"
                        },
                        new
                        {
                            Id = new Guid("12d76734-5e06-4c1e-88f4-8978b7edf710"),
                            Nombre = "Soporte y Mantenimiento"
                        },
                        new
                        {
                            Id = new Guid("3ffa7de0-1e20-4ec2-8cfb-7cf614723fc0"),
                            Nombre = "Servicios Profesionales"
                        });
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("RazonSocial")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Cobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComprobantePagoPath")
                        .HasColumnType("text");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoDePago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("UsuarioIdCreador");

                    b.ToTable("Cobros", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.CuentaPorCobrar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<bool>("Pagada")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.ToTable("CuentasPorCobrar", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.CuentaPorPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("ComprobantePagoPath")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("FacturaCompraPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CuentasPorPagar", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DiasCredito")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoAbonoInicial")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalSinImpuestos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FacturaDetalles", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalleConsumoLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadConsumida")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacturaDetalleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacturaDetalleId");

                    b.HasIndex("LoteId");

                    b.ToTable("FacturaDetalleConsumoLotes", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaSRI", b =>
                {
                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaveAcceso")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAutorizacion")
                        .HasColumnType("text");

                    b.Property<string>("RespuestaSRI")
                        .HasColumnType("text");

                    b.Property<string>("RideUrl")
                        .HasColumnType("text");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("text");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("text");

                    b.HasKey("FacturaId");

                    b.ToTable("FacturasSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Impuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoSRI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSRI")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Impuestos", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadComprada")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioCompraUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroNotaCredito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonModificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalSinImpuestos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.ToTable("NotasDeCredito", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("DescuentoAplicado")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NotaDeCreditoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NotaDeCreditoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("NotaDeCreditoDetalles", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoSRI", b =>
                {
                    b.Property<Guid>("NotaDeCreditoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaveAcceso")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAutorizacion")
                        .HasColumnType("text");

                    b.Property<string>("RespuestaSRI")
                        .HasColumnType("text");

                    b.Property<string>("RideUrl")
                        .HasColumnType("text");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("text");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("text");

                    b.HasKey("NotaDeCreditoId");

                    b.ToTable("NotasDeCreditoSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManejaInventario")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManejaLotes")
                        .HasColumnType("boolean");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("StockTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioIdCreador")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoPrincipal")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.ProductoImpuesto", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImpuestoId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductoId", "ImpuestoId");

                    b.HasIndex("ImpuestoId");

                    b.ToTable("ProductoImpuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3b1b4a9-2f7b-4e6a-9f6b-1c2c3d4e5f6a"),
                            Descripcion = "Acceso total al sistema.",
                            EstaActivo = true,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("e2a87c46-e5b3-4f9e-8c6e-1f2a3b4c5d6e"),
                            Descripcion = "Puede gestionar clientes y facturas.",
                            EstaActivo = true,
                            Nombre = "Vendedor"
                        },
                        new
                        {
                            Id = new Guid("f5b8c9d0-1a2b-3c4d-5e6f-7a8b9c0d1e2f"),
                            Descripcion = "Puede gestionar productos, compras e inventario.",
                            EstaActivo = true,
                            Nombre = "Bodeguero"
                        });
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Secuencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UltimoSecuencialFactura")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Secuenciales", (string)null);
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9b1b4d3-3f7b-4e6a-9f6b-1c2c3d4e5f6b"),
                            Email = "admin@facturassri.com",
                            EstaActivo = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$KnYr45JSbCoMg4Jtkg0GXegC7SegKYTidLxFYYljNwtLH0l024qLG",
                            PrimerApellido = "Aether",
                            PrimerNombre = "Admin"
                        });
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");

                    b.HasData(
                        new
                        {
                            UsuarioId = new Guid("a9b1b4d3-3f7b-4e6a-9f6b-1c2c3d4e5f6b"),
                            RolId = new Guid("d3b1b4a9-2f7b-4e6a-9f6b-1c2c3d4e5f6a")
                        });
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.AjusteInventario", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Cobro", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithMany("Cobros")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioIdCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.CuentaPorCobrar", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.CuentaPorPagar", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Factura", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalleConsumoLote", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.FacturaDetalle", "FacturaDetalle")
                        .WithMany("ConsumosDeLote")
                        .HasForeignKey("FacturaDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaDetalle");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaSRI", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithOne("InformacionSRI")
                        .HasForeignKey("FacturasSRI.Domain.Entities.FacturaSRI", "FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Lote", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCredito", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("NotasDeCredito")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoDetalle", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.NotaDeCredito", "NotaDeCredito")
                        .WithMany("Detalles")
                        .HasForeignKey("NotaDeCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaDeCredito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCreditoSRI", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.NotaDeCredito", "NotaDeCredito")
                        .WithOne("InformacionSRI")
                        .HasForeignKey("FacturasSRI.Domain.Entities.NotaDeCreditoSRI", "NotaDeCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaDeCredito");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Producto", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.ProductoImpuesto", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Impuesto", "Impuesto")
                        .WithMany("ProductoImpuestos")
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Producto", "Producto")
                        .WithMany("ProductoImpuestos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impuesto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("FacturasSRI.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturasSRI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("NotasDeCredito");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Cobros");

                    b.Navigation("Detalles");

                    b.Navigation("InformacionSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Navigation("ConsumosDeLote");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Impuesto", b =>
                {
                    b.Navigation("ProductoImpuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.NotaDeCredito", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("InformacionSRI");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("ProductoImpuestos");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("FacturasSRI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
